name: sys_map
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - astropy
  - matplotlib
  - healpy
  - emcee
  - scikit-learn>=1.3
  - pandas
  - pytest
  - pytest-cov
  - pip
  - pip:
    - jax[cpu]
    - treecorr
    - sphinx
    - sphinx-rtd-theme
    - myst-parser
    - corrfunc
